// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://dsefywdbmintbgnbytze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzZWZ5d2RibWludGJnbmJ5dHplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcxOTY5MDIsImV4cCI6MjA5Mjc3MjkwMn0.WVLW_ygW0VNnPwFF8C16TPJ9oInjCW4ySq0hGIjuQfg";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);